### ISSUE TITLE
Analtyics Reporting v4

### ISSUE THREAD

**Issue by russelltaylor05** [maximepvrt/angular-google-gapi#67]
Trying to get this working for v4 of the Google Analytics Reporting API. I've got it working for v3, but keep getting 404 errors when using v4. 

Does this module support v4?

This is what I'm trying:

```
GApi.load('analyticsreporting','v4')
```

and

```
GApi.load('analytics','v4')
```

**Comment by bdurrer** [comment]
That's not an issue with this module, since it just passes the api_name and api_version to the discovery service. The module itself is generic (well, besides the oauth it uses to authenticate you), you can load whatever google api you want.

According to the discovery service, the following is the correct one:
`GApi.load('analyticsreporting', 'v4')`

The analytics API has no version 4, only a version 3. 
`GApi.load('analytics', 'v3')`

you can use the discovery api inside the google api explorer to figure:
https://developers.google.com/apis-explorer/?hl=de#s/discovery/v1/discovery.apis.list?name=analyticsreporting&_h=3&
